apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o8swffqrv-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o8swffqrv-java-quarkus-gitops